### ISSUE TITLE
Forking of the repo

### ISSUE THREAD

**Issue by SiddarthNilol** [analytics-club-iitm/Daily-Sessions#13]
do we have to fork the repo every day to get the repo updated?

**Comment by MukundVarmaT** [comment]
@SiddarthNilol 
Hey, you don't need to. As mentioned in the instructions to submit an issue, I have mentioned that you can add the main repo as another remote. So this becomes like another origin for you. Do that by ```git remote add main "https://github.com/analytics-club-iitm/Daily-Sessions.git"``` and  hence this repo is referred to by main. 

A remote is like a reference to your git folder hosted online. 

So next time you want to update your local repo of the fork, just do ```git fetch main master``` and ```git merge main/master```. This should update your local repo with the updates in this main repo.
To push that to your fork just add those files and push it to the remote called origin which refers to your forked repo.

Check this out the second section in this [link](https://github.com/analytics-club-iitm/Daily-Sessions/blob/master/Git/submit_task.md)

**And by seeing your commit info I don't think you have used the git command line. Please make sure to do that as it has a lot of options.**

**Comment by Anit-G** [comment]
how do I upload task 2 to the master branch of Daily sessions

**Comment by MukundVarmaT** [comment]
@Anit-G I didn't understand by what you mean by upload to daily sessions. Do you mean your forked repo or where?

**Comment by SiddarthNilol** [comment]
By doing git merge main/master
I'm getting something like this 👇

**Comment by MukundVarmaT** [comment]
@SiddarthNilol I am not able to see anything?

**Comment by SiddarthNilol** [comment]
There's a photo uploaded

**Comment by MukundVarmaT** [comment]
@SiddarthNilol I don't see any photos here

Attach them by dragging and dropping also check the preview to see if you can view them

**Comment by SiddarthNilol** [comment]
![IMG_20200327_174541](https://user-images.githubusercontent.com/53142172/77759660-1aab7300-705b-11ea-92b0-b2a14141dea1.jpg)

**Comment by MukundVarmaT** [comment]
@SiddarthNilol Hey sorry I didn't see your message. Yeah, so it's just asking a message for the merge you have done. 
To move forward from here ```press ESC``` and then type ```:wq``` this means to save and exit. This comes up at the bottom of the terminal as you type this. It should then merge. Whenever we merge a commit is also made and hence it's asking for a message.

**Comment by SiddarthNilol** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/53142172/77785079-a6d09100-7081-11ea-930f-15226dce57da.png)
I'm not able to get a new prompt after doing "git log --all --oneline --decorate"

**Comment by MukundVarmaT** [comment]
@SiddarthNilol  Once again the same thing. See the colon on the bottom left. type ```wq``` and hit enter it will close.

**Comment by SiddarthNilol** [comment]
Cool! Got it. Thanks

**Comment by MukundVarmaT** [comment]
@SiddarthNilol Hey in case everything is fine please close this issue. You can always open another one in case something pops up.
