### ISSUE TITLE
Regarding retrieval of lost cloned directory along with modified things (directories and files in it)

### ISSUE THREAD

**Issue by sv3048** [analytics-club-iitm/Daily-Sessions#28]
Hi there,
I have my doubt related to github. I few months back cloned a directory from github and I am working in it. But somehow I was however not intented to delete it, by mistake deleted th edirectory. Is there any way (how should I properly checkout whole directory) so that I can get the directory along with changes made in it. Thanks in advance...for your valuable suggestion.

**Comment by MukundVarmaT** [comment]
Hey,
Git tracks the files in a specific folder. Now if you deleted the entire folder there is no way you can retrieve it unless there git is tracking the folder itself. (something like a folder inside a repository). 

So if that is the case something can be done else I suggest looking at your trash :P

**Comment by sv3048** [comment]
Thanks a lot for reply.
I have checked. But actually inside that directory there was not any .git directory. That directory was in this  path and this path has the .git directory(I searched from backside in this path but only in PlotsConfigurations{Please have a look on the below path} has .git directory) . So Can I still get it?
and how can I check the trash. I am sorry. But I am really new. So where can I find this trash directory.
/Framework/CMSSW_10_2_15/src/PlotsConfigurations/Configurations
Thanks in advance!

**Comment by MukundVarmaT** [comment]
I really didnt understand what you meant. So correct me if I am wrong you had a folder with some files tracked by git and you deleted the entire folder. And the directory containing this folder is not tracked by git right?

**Comment by sv3048** [comment]
Yes...but since its a chain of directories. So the previous directory has
.git directory. I don't think that can help me in getting back again my
lost directories and files. Right?

**Comment by MukundVarmaT** [comment]
You can if you had made a commit or if you have stashed the folder. You can just directly ping me so that I can help you out better.

**Comment by sv3048** [comment]
No..I haven't made any commit that is my main problem. I didn't ever thought
of deleting. Okay.. ...Thanks...Then I think It cant be done. The second thing
you told me to check trash, that can you pls tell where should I go..for that.

Thanks

**Comment by MukundVarmaT** [comment]
I meant the recycle bin if you are using windows or the trash folder in case of Linux. That wasn't meant to be actual advice :P

**Comment by sv3048** [comment]
Ahh...Okay...I got it...
Thanks  ...for helping me in this issue. Thanks a lot for your time.

regards
Sadhana
